cache: yarn
language: node_js
node_js:
  - "14"

jobs:
  include:
    - stage: test
      script:
        - yarn compile
        - yarn lint
    - stage: deploy
      if: branch = master
      cache:
        directories:
          - $HOME/.cache/yarn
          - node_modules
          - .next/cache
      before_script:
        - mkdir -p $HOME/.ssh
        - echo "$SSH_KEY" | base64 -d > $HOME/.ssh/id_rsa
        - chmod 600 $HOME/.ssh/id_rsa
      script:
        - ASSET_PREFIX='/pcnp-landing' BASE_PATH='/pcnp-landing' yarn build
        - touch out/.nojekyll
        - git add out && git commit -am 'deploy'
        - git remote add upstream git@github.com:PCNP/pcnp-landing.git
        - git subtree split --prefix out -b gh-pages
        - git push -f upstream gh-pages:gh-pages
        - git branch -D gh-pages
