cache: yarn
language: node_js
node_js:
  - "14"

jobs:
  include:
    - stage: test
      script:
        - yarn compile
        - yarn lint
    - stage: deploy
      if: branch = master
      cache:
        yarn: true
        directories:
          - .next/cache
      script:
        - yarn build
