cache: yarn
language: node_js
node_js:
  - "14"

jobs:
  include:
    - stage: test
      script:
        - yarn compile
        - yarn lint
    - stage: deploy
      if: branch = master
      cache:
        directories:
          - $HOME/.cache/yarn
          - node_modules
          - .next/cache
      before_script:
        - mkdir -p $HOME/.ssh
        - echo "$SSH_KEY" | base64 -d > $HOME/.ssh/id_rsa
      script:
        - BASE_PATH='/pcnp-landing' yarn build
        - ouch out/.nojekyll
        - git add out && git commit -am 'deploy'
        - git subtree push --prefix out origin gh-pages
